name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "bin.boixu.com"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "2737dd2db6834736ad8953cd19157510"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://bin.boixu.com"

# url to repo, displayed in index page
REPO = "https://github.com/boixu/pastebin-worker"

# url to favicon
FAVICON = "https://boixu.com/pic.png"

# the name displayed in TOS
TOS_MAINTAINER = "Boixu"

# the email displayed in TOS
TOS_MAIL = "pb@boixu.com"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
